kind: Deployment
apiVersion: apps/v1
metadata:
  name: control-center
  namespace: ersin-test 
labels:
  deployment: control-center
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: control-center
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: control-center
    spec:
      volumes:
        - name: generic
          persistentVolumeClaim:
            claimName: generic
        - name: empty1
          emptyDir: {}
      enableServiceLinks: false
      containers:
        - resources: 
            limits:
              memory: 1Gi
          name: control-center
          env: 
            - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
              value: broker:29092
            - name: CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER
              value: connect:8083
            - name: CONTROL_CENTER_KSQL_KSQLDB1_URL
              value: http://ksqldb-server:8088
            - name: CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL
              value: http://localhost:8088
            - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
              value: http://schema-registry:8081
            - name: CONTROL_CENTER_REPLICATION_FACTOR
              value: '1'
            - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
              value: '1'
            - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
              value: '1'
            - name: CONFLUENT_METRICS_TOPIC_REPLICATION
              value: '1'
            - name: PORT
              value: '9021'
          ports:
            - containerPort: 9021
              protocol: TCP 
          volumeMounts:
            - name: generic
              mountPath: /etc/ksqldb-server/
            - name: empty1
              mountPath: /usr/logs/
          image: >-
            confluentinc/cp-enterprise-control-center:7.0.1
