kind: Service
apiVersion: v1
metadata:
  name: connect
  namespace: ersin-test 
  annotations:
    generated.by: ersingulbahar 
spec:
  ports:
    - name: 8083-tcp
      protocol: TCP
      port: 8083
      targetPort: 8083
  selector:
    deployment: connect
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
status:
  loadBalancer: {}
