kind: Service
apiVersion: v1
metadata:
  name: schema-registry
  namespace: ersin-test 
  annotations:
    generated.by: ersingulbahar 
spec:
  ports:
    - name: 8081-tcp
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    deployment: schema-registry
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
status:
  loadBalancer: {}
